### PR TITLE
Allow G (gigabytes, 2^30 scaling factor) modifier in limit builtin command

### PR DESCRIPTION
**Pull request by AMDmi3**

### CODE REVIEW

**Comment by danielshahaf** [comment]
Could you please send this to zsh-workers@zsh.org?  The zsh project doesn't use github.

**Comment by AMDmi3** [comment]
Done, no reaction.

**Comment by danielshahaf** [comment]
Applied by @bartschaefer in 1ea94513cc329c682d1afeaecd3bbfc3c66882ab. Thanks for the patch!

**Comment by AMDmi3** [comment]
Thank you!

**Pull request closed without merging**
