### PR TITLE
Fix unix command lldb tab-completion

### PR DESCRIPTION
**Pull request by Semnodime**
The --arguments are space (` `) separated, not equal-sign (`=`) separated.
lldb --correct c_arg --wrong=w_arg

### CODE REVIEW

**Comment by okapia** [comment]
Thanks for the contribution, I needed to tweak this slightly as you had changed the equals to a space where space is the default so it needed to be empty. Otherwise from that, It has been merged in ed160f26.

**Comment by Semnodime** [comment]
When will the merge appear as update?

**Comment by okapia** [comment]
I'm not certain that I follow what your question means. If you mean when will there be a 5.9 release of zsh with the change, I can't answer that because I'm not the zsh release manager. We're rather behind on merging patches at the moment so there would be a fair amount of work just to get it in shape. If you're talking about the github pull request merge status, I'm not sure how well that follows because the github repo is just a mirror so isn't used directly.

**Comment by danielshahaf** [comment]
> I'm not certain that I follow what your question means. If you mean when will there be a 5.9 release of zsh with the change, I can't answer that because I'm not the zsh release manager. We're rather behind on merging patches at the moment so there would be a fair amount of work just to get it in shape. If you're talking about the github pull request merge status, I'm not sure how well that follows because the github repo is just a mirror so isn't used directly.

I don't think we should block a 5.9 release on merging all outstanding patches: there's been more than enough patches merged after 5.8 that are awaiting the next train.  Any patches that don't make the 5.9 train will simply have to wait for 5.10.

Anyway, this is a discussion for -workers@.  @Semnodime, feel free to start a thread about scheduling 5.9.

**Pull request closed without merging**
